[2024-03-30T02:21:10.693+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T02:16:00.471001+00:00 [queued]>
[2024-03-30T02:21:10.700+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T02:16:00.471001+00:00 [queued]>
[2024-03-30T02:21:10.701+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-03-30T02:21:10.722+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): load_data_to_snowflake> on 2024-03-30 02:16:00.471001+00:00
[2024-03-30T02:21:10.734+0000] {standard_task_runner.py:60} INFO - Started process 62 to run task
[2024-03-30T02:21:10.737+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'migrate_student_data_to_snowflake', 'load_data_to_snowflake', 'manual__2024-03-30T02:16:00.471001+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/student_data_migration.py', '--cfg-path', '/tmp/tmp8os6b149']
[2024-03-30T02:21:10.742+0000] {standard_task_runner.py:88} INFO - Job 168: Subtask load_data_to_snowflake
[2024-03-30T02:21:10.835+0000] {task_command.py:423} INFO - Running <TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T02:16:00.471001+00:00 [running]> on host abcdb457cf2c
[2024-03-30T02:21:11.131+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='migrate_student_data_to_snowflake' AIRFLOW_CTX_TASK_ID='load_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T02:16:00.471001+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T02:16:00.471001+00:00'
[2024-03-30T02:21:11.134+0000] {connection.py:386} INFO - Snowflake Connector for Python Version: 3.7.1, Python Version: 3.8.19, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
[2024-03-30T02:21:11.136+0000] {connection.py:1211} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-03-30T02:21:12.049+0000] {cursor.py:1032} INFO - query: [CREATE DATABASE IF NOT EXISTS VIEWS_STUDENTS]
[2024-03-30T02:21:12.196+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:21:12.197+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:21:12.198+0000] {cursor.py:1032} INFO - query: [USE DATABASE VIEWS_STUDENTS]
[2024-03-30T02:21:12.339+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:21:12.340+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:21:12.341+0000] {cursor.py:1032} INFO - query: [CREATE SCHEMA IF NOT EXISTS STUDENTS_SEMANTIC]
[2024-03-30T02:21:12.411+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:21:12.412+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:21:12.412+0000] {cursor.py:1032} INFO - query: [USE SCHEMA STUDENTS_SEMANTIC]
[2024-03-30T02:21:12.481+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:21:12.482+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:21:12.483+0000] {cursor.py:1032} INFO - query: [CREATE OR REPLACE TABLE FINAL_MERGED ( student_id VARCHAR, name VARCHAR, grades ...]
[2024-03-30T02:21:12.799+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:21:12.800+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:21:12.804+0000] {cursor.py:1032} INFO - query: [COPY INTO FINAL_MERGED (student_id,name,grades,missed_days) FROM VALUES ('S001',...]
[2024-03-30T02:21:12.905+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:21:12.913+0000] {student_data_migration.py:143} ERROR - Error loading data into Snowflake: 001003 (42000): 01b35308-0000-3e11-0000-0000499126bd: SQL compilation error:
syntax error line 1 at position 65 unexpected 'VALUES'.
[2024-03-30T02:21:12.914+0000] {connection.py:734} INFO - closed
[2024-03-30T02:21:12.946+0000] {connection.py:740} INFO - No async queries seem to be running, deleting session
[2024-03-30T02:21:12.992+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/student_data_migration.py", line 140, in load_data_to_snowflake
    cursor.execute(query + values)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 1136, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01b35308-0000-3e11-0000-0000499126bd: SQL compilation error:
syntax error line 1 at position 65 unexpected 'VALUES'.
[2024-03-30T02:21:12.998+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=migrate_student_data_to_snowflake, task_id=load_data_to_snowflake, execution_date=20240330T021600, start_date=20240330T022110, end_date=20240330T022112
[2024-03-30T02:21:13.008+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 168 for task load_data_to_snowflake (001003 (42000): 01b35308-0000-3e11-0000-0000499126bd: SQL compilation error:
syntax error line 1 at position 65 unexpected 'VALUES'.; 62)
[2024-03-30T02:21:13.045+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-30T02:21:13.058+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
